apiVersion: apps/v1beta1
kind: Deployment
metadata:
  name: aplicacao-deployment
spec:  
  template:
    metadata:
      labels:
        name: aplicacao-pod
    spec:
      containers:
        - name: container-fastabc-app
          image: rodimes/fastabc-app
          ports:
            - containerPort: 8080
